spring:
  datasource:
    # TODO MVCC=TRUE란 조건 찾아보기
    url: jdbc:h2:~/docker/h2/data/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      # 애플리케이션 실행 시점에 테이블을 drop 하고, 다시 생성
      ddl-auto: create
    properties:
      hibernate:
        # System.out 에 하이버네이트 실행 SQL 출력
#        show_sql: true
        format_sql: true

logging.level:
  # logger를 통해 하이버네이트 실행 SQL
  org.hibernate.SQL: debug
  # 쿼리 호출 시 파라미터 출력
  org.hibernate.type: trace
