# https://docs.spring.io/spring-boot/docs/2.1.7.RELEASE/reference/html/common-application-properties.html
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    # TODO MVCC=TRUE란 조건 찾아보기 -> DONE
    url: jdbc:h2:~/docker/h2/data/jpashopoptimize
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      # 애플리케이션 실행 시점에 테이블을 drop 하고, 다시 생성
      ddl-auto: create
    properties:
      hibernate:
        # System.out 에 하이버네이트 실행 SQL 출력
#        show_sql: true
        format_sql: true
        # 주문조회 v3.1 성능 최적화 설정 > 정해진 갯수만큼 먼저 읽어옴
        default_batch_fetch_size: 1000

logging.level:
  # logger를 통해 하이버네이트 실행 SQL
  org.hibernate.SQL: debug
  # 쿼리 호출 시 파라미터 출력
  org.hibernate.type: trace


